### ISSUE TITLE
Move the code to this repo

### ISSUE THREAD

**Issue by kanitw** [vega/voyager-electron#1]
It will be easier for us to maintain in a long run if the repo resides under Vega organization. 

@tafsiri could you please submit a PR to push the code here instead?

Thank you.  :)

**Comment by tafsiri** [comment]
@kanitw so it turns out that you can't PR into an empty repo. In the process of discovering this i ended up making `add-voyager-electron` the default branch in github. I have since pushed a master branch. I don't have access to the repo settings, could you make master the default branch and i can delete the other one.

**Comment by kanitw** [comment]
Done :)

**Comment by tafsiri** [comment]
Thanks!
